### ISSUE TITLE
Issue where israeli government has accessed guest account

### ISSUE THREAD

**Issue by LeibYaakov91** [GrapheneOS/discuss.grapheneos.org#4]
The guest account has been enabled ,unless I lockdown my main user and force end session , then while in lockdown I access any secondary user and must be in LTE Only mode. Then the force access of guest user is disabled . without this they access guest.

**Comment by LeibYaakov91** [comment]
When I do not force the main user into lockdown and have LTE only  enabled to prevent this , and I open my secondary user then guest account appears. I choose end session, then when I choose end session from main lock screen a blue background appears where they have gained access and then I can end their temporary guest access, this must be looked into , I am on Blue Jay 6a stable. Please add a way to force disable any Guest Possibility in a hardened manner as such. Please update me

**Comment by thestinger** [comment]
Guest is disabled by default. This is the wrong place to post this and what you're posting is clearly not accurate.
